services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    #UI menu item
    EzPlatform\ActivitiesLog\EventListener\ConfigureMenuListener:
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }
    #trigger UI events
    EzPlatform\ActivitiesLog\EventSubscriber\ActivitiesLog\:
        resource: '../../../lib/EventSubscriber/ActivitiesLog/*'
