admin_log_activities_all:
    path: /activitieslog/all
    controller: 'EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:allActivitiesAction'
admin_log_activities_my:
    path: /activitieslog/my
    controller: 'EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:myActivitiesAction'