admin_log_cockpit_all:
    path: /activitieslog/cockpit/all
    controller: 'EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:cockpitAllAction'
admin_log_cockpit_my:
    path: /ActivitiesLog/cockpit/my
    controller: 'EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:cockpitMyAction'