parameters:
    activitiesLog.ui_panel.pagination_limit: 5
    activitiesLog.user_tab.pagination_limit: 5
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    EzPlatform\ActivitiesLogBundle\Controller\:
#        resource: '../../Controller'

    EzPlatform\ActivitiesLogBundle\Entity\ActivitiesLog: ~

    #UI Interface
    EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:
        arguments:
            $activitiesLogUiPanelPaginationLimit: '%activitiesLog.ui_panel.pagination_limit%'
            $user: '@EzPlatform\ActivitiesLog\Repository\User'

    #helper to get more information about the event for the UI Interface
    EzPlatform\ActivitiesLogBundle\Twig\ActivitiesLogExtension:
        tags:
            - { name: twig.extension }

    EzPlatform\ActivitiesLog\Repository\Storage\Doctrine\ActivitiesLogRepository: ~
    #Pagination and queryBuilder results for UI Interface
    EzPlatform\ActivitiesLog\Repository\Services\ActivitiesLogRepositoryService: ~

    #Tab helper to get current logged in user
    EzPlatform\ActivitiesLog\Repository\User: ~

    #Add view parameters
    EzPlatform\ActivitiesLog\EventSubscriber\ActivitiesLogTabSubscriber:
        arguments:
            $activitiesLogUserTabPaginationLimit: '%activitiesLog.user_tab.pagination_limit%'