parameters:
    activitiesLog.ui_panel.pagination_limit: 5
    activitiesLog.user_tab.pagination_limit: 5
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    EzPlatform\ActivitiesLogBundle\Controller\:
#        resource: '../../Controller'

    #UI menu item
    EzPlatform\ActivitiesLog\EventListener\ConfigureMenuListener:
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    #UI Interface
    EzPlatform\ActivitiesLogBundle\Controller\ActivitiesLogController:
        arguments:
            $activitiesLogUiPanelPaginationLimit: '%activitiesLog.ui_panel.pagination_limit%'
            $user: '@EzPlatform\ActivitiesLog\Repository\User'

    #trigger UI events
    EzPlatform\ActivitiesLog\EventSubscriber\ActivitiesLogSignalListener: ~

    #helper to get more information about the event for the UI Interface
    EzPlatform\ActivitiesLogBundle\Twig\ActivitiesLogExtension:
        tags:
            - { name: twig.extension }

    #Pagination and queryBuilder results for UI Interface
    EzPlatform\ActivitiesLog\Repository\Services\ActivitiesLogRepositoryService: ~

    #Tab helper to get current logged in user
    EzPlatform\ActivitiesLog\Repository\User: ~

    #Activities tab only for users
    EzPlatform\ActivitiesLog\Tab\LocationView\ActivitiesLogTab:
        arguments:
            $userContentTypeIdentifier: '$user_content_type_identifier$'
        tags:
            - { name: ezplatform.tab, group: location-view }

    #Add view parameters
    EzPlatform\ActivitiesLog\EventSubscriber\ActivitiesLogTabSubscriber:
        arguments:
            $activitiesLogUserTabPaginationLimit: '%activitiesLog.user_tab.pagination_limit%'